Update jaccard_similarity.py
Typo in `jaccard_list_similarity` leads to incorrect errors:
```
File /opt/conda/lib/python3.9/site-packages/simphile/jaccard_similarity.py:40, in jaccard_list_similarity(list_a, list_b)
     39 def jaccard_list_similarity(list_a, list_b):
---> 40     assert len(list_a) > 0 or len(list_b > 0), "at least one list needs to have elements"
     41     intersected = intersect(list_a, list_b)
     42     combined = list_a + list_b

TypeError: '>' not supported between instances of 'list' and 'int'
```